// Code generated by protoc-gen-go. DO NOT EDIT.
// versions: 4.0.0+
// source: pkg/protocol/message.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomState_State int32

const (
	RoomState_WAITING  RoomState_State = 0
	RoomState_PLAYING  RoomState_State = 1
	RoomState_FINISHED RoomState_State = 2
)

func (x RoomState_State) Enum() *RoomState_State {
	p := new(RoomState_State)
	*p = x
	return p
}

func (x RoomState_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomState_State) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_protocol_message_proto_enumTypes[0].Descriptor()
}

func (RoomState_State) Type() protoreflect.EnumType {
	return &file_pkg_protocol_message_proto_enumTypes[0]
}

func (x RoomState_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*ClientMessage_Login
	//	*ClientMessage_JoinRoom
	//	*ClientMessage_Input
	//	*ClientMessage_Heartbeat
	Payload isClientMessage_Payload `protobuf_oneof:"payload"`
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Login struct {
	Login *LoginRequest `protobuf:"bytes,1,opt,name=login,proto3,oneof"`
}

type ClientMessage_JoinRoom struct {
	JoinRoom *JoinRoomRequest `protobuf:"bytes,2,opt,name=join_room,json=joinRoom,proto3,oneof"`
}

type ClientMessage_Input struct {
	Input *PlayerInput `protobuf:"bytes,3,opt,name=input,proto3,oneof"`
}

type ClientMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

func (*ClientMessage_Login) isClientMessage_Payload() {}

func (*ClientMessage_JoinRoom) isClientMessage_Payload() {}

func (*ClientMessage_Input) isClientMessage_Payload() {}

func (*ClientMessage_Heartbeat) isClientMessage_Payload() {}

func (m *ClientMessage) GetPayload() isClientMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ClientMessage) GetLogin() *LoginRequest {
	if x, ok := x.GetPayload().(*ClientMessage_Login); ok {
		return x.Login
	}
	return nil
}

func (x *ClientMessage) GetJoinRoom() *JoinRoomRequest {
	if x, ok := x.GetPayload().(*ClientMessage_JoinRoom); ok {
		return x.JoinRoom
	}
	return nil
}

func (x *ClientMessage) GetInput() *PlayerInput {
	if x, ok := x.GetPayload().(*ClientMessage_Input); ok {
		return x.Input
	}
	return nil
}

func (x *ClientMessage) GetHeartbeat() *Heartbeat {
	if x, ok := x.GetPayload().(*ClientMessage_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

type ServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*ServerMessage_Login
	//	*ServerMessage_JoinRoom
	//	*ServerMessage_Frame
	//	*ServerMessage_RoomState
	//	*ServerMessage_Error
	//	*ServerMessage_Heartbeat
	Payload isServerMessage_Payload `protobuf_oneof:"payload"`
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Login struct {
	Login *LoginResponse `protobuf:"bytes,1,opt,name=login,proto3,oneof"`
}

type ServerMessage_JoinRoom struct {
	JoinRoom *JoinRoomResponse `protobuf:"bytes,2,opt,name=join_room,json=joinRoom,proto3,oneof"`
}

type ServerMessage_Frame struct {
	Frame *FrameData `protobuf:"bytes,3,opt,name=frame,proto3,oneof"`
}

type ServerMessage_RoomState struct {
	RoomState *RoomState `protobuf:"bytes,4,opt,name=room_state,json=roomState,proto3,oneof"`
}

type ServerMessage_Error struct {
	Error *ErrorResponse `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type ServerMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,6,opt,name=heartbeat,proto3,oneof"`
}

func (*ServerMessage_Login) isServerMessage_Payload() {}

func (*ServerMessage_JoinRoom) isServerMessage_Payload() {}

func (*ServerMessage_Frame) isServerMessage_Payload() {}

func (*ServerMessage_RoomState) isServerMessage_Payload() {}

func (*ServerMessage_Error) isServerMessage_Payload() {}

func (*ServerMessage_Heartbeat) isServerMessage_Payload() {}

func (m *ServerMessage) GetPayload() isServerMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ServerMessage) GetLogin() *LoginResponse {
	if x, ok := x.GetPayload().(*ServerMessage_Login); ok {
		return x.Login
	}
	return nil
}

func (x *ServerMessage) GetJoinRoom() *JoinRoomResponse {
	if x, ok := x.GetPayload().(*ServerMessage_JoinRoom); ok {
		return x.JoinRoom
	}
	return nil
}

func (x *ServerMessage) GetFrame() *FrameData {
	if x, ok := x.GetPayload().(*ServerMessage_Frame); ok {
		return x.Frame
	}
	return nil
}

func (x *ServerMessage) GetRoomState() *RoomState {
	if x, ok := x.GetPayload().(*ServerMessage_RoomState); ok {
		return x.RoomState
	}
	return nil
}

func (x *ServerMessage) GetError() *ErrorResponse {
	if x, ok := x.GetPayload().(*ServerMessage_Error); ok {
		return x.Error
	}
	return nil
}

func (x *ServerMessage) GetHeartbeat() *Heartbeat {
	if x, ok := x.GetPayload().(*ServerMessage_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LoginRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success   bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type JoinRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JoinRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type JoinRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success     bool          `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RoomId      string        `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerIndex int32         `protobuf:"varint,3,opt,name=player_index,json=playerIndex,proto3" json:"player_index,omitempty"`
	Players     []*PlayerInfo `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JoinRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRoomResponse) GetPlayerIndex() int32 {
	if x != nil {
		return x.PlayerIndex
	}
	return 0
}

func (x *JoinRoomResponse) GetPlayers() []*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

type PlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Index    int32  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Ready    bool   `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PlayerInfo) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerInfo) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PlayerInfo) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type PlayerInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Frame       uint32 `protobuf:"varint,1,opt,name=frame,proto3" json:"frame,omitempty"`
	PlayerIndex int32  `protobuf:"varint,2,opt,name=player_index,json=playerIndex,proto3" json:"player_index,omitempty"`
	InputData   []byte `protobuf:"bytes,3,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PlayerInput) GetFrame() uint32 {
	if x != nil {
		return x.Frame
	}
	return 0
}

func (x *PlayerInput) GetPlayerIndex() int32 {
	if x != nil {
		return x.PlayerIndex
	}
	return 0
}

func (x *PlayerInput) GetInputData() []byte {
	if x != nil {
		return x.InputData
	}
	return nil
}

type FrameData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Frame  uint32         `protobuf:"varint,1,opt,name=frame,proto3" json:"frame,omitempty"`
	Inputs []*PlayerInput `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
}

func (x *FrameData) Reset() {
	*x = FrameData{}
}

func (x *FrameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameData) ProtoMessage() {}

func (x *FrameData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FrameData) GetFrame() uint32 {
	if x != nil {
		return x.Frame
	}
	return 0
}

func (x *FrameData) GetInputs() []*PlayerInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type RoomState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State        RoomState_State `protobuf:"varint,1,opt,name=state,proto3,enum=protocol.RoomState_State" json:"state,omitempty"`
	CurrentFrame uint32          `protobuf:"varint,2,opt,name=current_frame,json=currentFrame,proto3" json:"current_frame,omitempty"`
}

func (x *RoomState) Reset() {
	*x = RoomState{}
}

func (x *RoomState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomState) ProtoMessage() {}

func (x *RoomState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RoomState) GetState() RoomState_State {
	if x != nil {
		return x.State
	}
	return RoomState_WAITING
}

func (x *RoomState) GetCurrentFrame() uint32 {
	if x != nil {
		return x.CurrentFrame
	}
	return 0
}

type Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ErrorResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_protocol_message_proto protoreflect.FileDescriptor

var file_pkg_protocol_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_protocol_message_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_protocol_message_proto_goTypes = []interface{}{}
var file_pkg_protocol_message_proto_depIdxs = []int32{}
